name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Cron job daily at 03:00
  schedule:
    - cron: '0 3 * * *'

jobs:
  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      # Run API specs then E2E specs
      - name: Run API tests
        run: npm run cy:backend
        continue-on-error: false

      - name: Run E2E (UI) tests
        run: npm run cy:frontend
        continue-on-error: false

      # Upload screenshots & videos (always, for debugging)
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
